DATA:
    ROOT: 'G:\\data\\ShanghaiTech\\shanghaitech_reorganized\\'
    TRAIN_FILE: './labels/Shanghaitech_train.txt'
    VAL_FILE: './labels/Shanghaitech_test.txt'
    DATASET: SHT
    NUM_CLIPS: 16
    NUM_FRAMES: 5
    FRAME_INTERVAL: 4
    NUM_CLASSES: 2
    LABEL_LIST: 'labels/traffic_2_labels.csv'
    FILENAME_TMPL: '{}.jpg'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 2
    ACCUMULATION_STEPS: 8